apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: emoji-search
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: emoji-search
    spec:
       containers:
       - name: characters
         image: 478841571343.dkr.ecr.ap-south-1.amazonaws.com/characters:v1
         ports:
         - containerPort: 3000
