apiVersion: v1
kind: Service
metadata:
  name: emoji-search
  labels:
    app: emoji-search
spec:
  selector:
    app: emoji-search
  ports:
  - port: 3000
    protocol: TCP
    nodePort: 30001
  type: LoadBalancer
